server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: demo-victim-app

failframe:
  enabled: ${FAILFRAME_ENABLED:true}
  api-key: ${FAILFRAME_API_KEY:failframe-local-dev-key}
  collector-url: ${FAILFRAME_COLLECTOR_URL:http://localhost:8080}
  service-name: ${FAILFRAME_SERVICE_NAME:demo-victim-app}
  environment: ${FAILFRAME_ENVIRONMENT:local}
